#!/usr/bin/env bash 


─ 
          ██                  
                                                                ███
          ██             ██                 ██████     ██   █
          ██           ██  ██   JACK    ██             ██  █               
          ██ @PHP57  ██    ██          ██              ██ █
          ██         ██      ██        ██               ███
          ██        ██        ██      ██    @PHP57     ███
          ██       ██  ████  ██      ██               ██ █
   ██    ██      ██            ██      ██              ██  █
   ███████     ██SOURCE BLACK██      ███████     ██   █
                                                                ███
                            BLACK ﹏ @BLACK_TEAM_3
                            تم تطوير وبرمجة السورس من قبل جاك ✾ 
-ـ-ـ-ـ-ـ-ــ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ--ـ-ـ-ـ-ـ
┊BLACK ‿ @PHP57
┊@PHP57 ‿ @PHP57
#-ـ-ـ-ـ-ـ-ــ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ-ـ--ـ-ـ-ـ-ـ
cd $(cd $(dirname $0); pwd)
 
RED='\033[0;31m'
SMAY='\033[0;36m' 
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'
Version=`lsb_release -rs | cut -f1 -d"."`

if [ "$Version" == "18" ]; then
echo -e "\033[0;31m\n~ Installing Depedencies For Ubuntu 18... \n\033[0m"
cd /lib/x86_64-linux-gnu/ && sudo ln -s libreadline.so.7.0 libreadline.so.6
wget "ibotcorp.com/files/compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb" && sudo dpkg -i compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb
rm compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb
fi


if [ ! -f "./TG" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Not Dwonload TG .
¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source BLACK${CNIL} . \n
\n\n"
chmod +x ./ins
./ins
exit;
fi

if [ ! -f "./inc/Token.txt" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Token Bot Not Found .
¦ NOW I Run File ${SMAY}./RUN.lua${WHITB} To Enter Data For You Bot${CNIL}. \n
\n\n"
lua ./inc/Run.lua
exit;
fi


TOKEN=`cat ./inc/Token.txt`
sudo chmod +x ./TG

if [ "$1" == "R" ] ; then
while(true) do
killall -q ./TG
sudo rm -fr ../.telegram-cli
./TG -s inc/Run.lua --bot=$TOKEN
done
else

if ! screen -list | grep -q "BLACK"; then
screen -S BLACK ./run R
fi
screen -S BLACK -X kill
screen -S BLACK ./run R
fi

